### ISSUE TITLE
Drawing slightly angled lines in textures on walls don't seem deterministic

### ISSUE THREAD

**Issue by AleksaHeler** [AleksaHeler/LPRS2_Emulator#2]
When lines barely angled from textures are rendered they dont go like -----____, but instead like --_-_-____.

![line_issue](https://user-images.githubusercontent.com/26066785/113710947-a4693400-96e4-11eb-95c5-2717940b3bc0.png)

**Comment by TrAceX99** [comment]
Ovo je do zaokruzivanja sigurno, moguce zbog onog int kasta umesto floor

**Comment by AleksaHeler** [comment]
Fixed it by using proper functions to round numbers, and always using the round down on horizontal line
